# Generated by Django 2.2.1 on 2019-10-07 19:37

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('dateofbith', models.DateField(blank=True, null=True, verbose_name='Birth-date')),
                ('dateofdeath', models.DateField(blank=True, null=True, verbose_name='Died')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Title')),
                ('summary', models.TextField(blank=True, null=True)),
                ('isbn', models.CharField(help_text='13 digit unique international code', max_length=20, verbose_name='ISBN')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bookcollection.Author')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='enter genre like fiction,action,romantic ', max_length=30, verbose_name='Genre')),
            ],
        ),
        migrations.CreateModel(
            name='Bookinstances',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='unique id for this part of the book across library', primary_key=True, serialize=False)),
                ('imprint', models.CharField(max_length=300)),
                ('due_back', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('m', 'Maintenance'), ('o', 'onloan'), ('r', 'reserved'), ('a', 'available')], default='m', help_text='Book Avalilability', max_length=40)),
                ('book', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bookcollection.Book')),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.ManyToManyField(help_text='select the genre for this book', to='bookcollection.Genre'),
        ),
    ]
