# Generated by Django 2.2.1 on 2019-10-25 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookcollection', '0002_bookinstances_borrower'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['title'], 'permissions': (('can_mark_returned', 'set book as returned '),)},
        ),
    ]
