# Generated by Django 2.2.1 on 2019-10-25 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookcollection', '0004_auto_20191025_1809'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookinstances',
            options={'ordering': ['id'], 'permissions': (('can_mark_returned', 'set book as returned '),)},
        ),
    ]
