# Generated by Django 2.2.1 on 2019-11-10 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookcollection', '0008_auto_20191110_1022'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookinstances',
            options={'ordering': ['id'], 'permissions': (('can_mark_returned', 'set book as returned '), ('can_renew', 'renew the book'), ('staff', 'for staff only'))},
        ),
    ]
