# Generated by Django 2.2.1 on 2019-11-10 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookcollection', '0010_auto_20191110_1705'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookinstances',
            old_name='book',
            new_name='book1',
        ),
    ]
